### ISSUE TITLE
Autocomplete slows down the entire site when there are a lot of issues

### ISSUE THREAD

**Issue by gabrielittner** [google/github-issue-mover#16]
It also happened on a local dev server. After I removed `gim_typeahead.dart` and all references too it the site worked normally.
The repo had ~100 open issues and 500+ total.

**Comment by nicolasgarnier** [comment]
Thanks for the report. It seems that the github client library is trying to always pull the same page when listing repos of organizations... Probably an issue on the GitHub client library. I'll file an issue with them. let see.

**Comment by nicolasgarnier** [comment]
Filed here: https://github.com/DirectMyFile/github.dart/issues/53

**Comment by ernestoalejo** [comment]
I found this error too; the count keeps going up and up (150k when I closed it)

**Comment by nicolasgarnier** [comment]
I just re-updated all dependencies and re-deployed to prod and the issue seems fixed now... Not sure what happened but it's now fixed!
