### ISSUE TITLE
Tools seems to be broken

### ISSUE THREAD

**Issue by dmolineus** [google/github-issue-mover#3]
I've tried your online tool. Unfortunately I get an error message than click on move issue:

```
Error creating new issue: NullError: Cannot call "ez" on null
```

It happens if i want to move one issue between two personal issues and also when trying to move an issue between 2 repos which belongs to an organization.

**Comment by ahundt** [comment]
I still get this error and it seems there is another issue dedicated to this:
https://github.com/google/github-issue-mover/issues/11

**Comment by boelle** [comment]
yep i just ran in to it today
