### ISSUE TITLE
Question: while moving issues, will it keep the issue under the same user?

### ISSUE THREAD

**Issue by fernandog** [google/github-issue-mover#46]
@nicolasgarnier
or will create the new issue under my github account?
will it movie all replies and etc?

I have an 2 repos in an organizarion:
the first one is the code
the second one is issue-tracker

I want to move all issues labeled as "feature-request" to a new repo named feature-requests
the problem is that I want the issues to remain associate with the user who opened in first place

**Comment by FichteFoll** [comment]
The issues will be associated with your account because all comments will be created by it.

Example: https://github.com/SublimeTextIssues/DefaultPackages/issues/111
